### ISSUE TITLE
32679 segmentation fault (core dumped)  axel -n 20

### ISSUE THREAD

**Issue by fuzihaofzh** [axel-download-accelerator/axel#140] opened 2018-01-01 02:30 UTC
Hi 
I use `axel -n 20 https://dumps.wikimedia.org/enwiki/20171220/enwiki-20171220-pages-articles.xml.bz2` and get:
`32679 segmentation fault (core dumped)  axel -n 20`
It seems some bugs here.

**Comment by ordex** [comment] 2018-01-01 12:37
I can't reproduce it here. Does it happen all the time?

**Comment by maplewizard** [comment] 2018-01-01 13:28
@ordex  Yes, I compile axel locally. Do you think that it was caused by some wrong version of the dependencies?

**Comment by ordex** [comment] 2018-01-01 13:33
can't exclude that. If you are compiling axel yourself, would you be able to compile it with debug symbols enabled and run it inside gdb ?

**Comment by maplewizard** [comment] 2018-01-01 13:56
Hi, the backtrace is shown as follow, could you please help to find the problem?
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed402700 (LWP 127519)]
0x00007fffeee11107 in do_ypcall () from /lib64/libnsl.so.1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.5.x86_64 keyutils
-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 l
ibselinux-2.5-6.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pcre-8.32-15.el7_2.1.x86_
64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007fffeee11107 in do_ypcall () from /lib64/libnsl.so.1
#1  0x00007fffeee115c2 in yp_match () from /lib64/libnsl.so.1
#2  0x00007fffef028f54 in _nss_nis_gethostbyname4_r () from /lib64/libnss_nis.so.2
#3  0x00007ffff7284378 in gaih_inet () from /lib64/libc.so.6
#4  0x00007ffff7287a6d in getaddrinfo () from /lib64/libc.so.6
#5  0x00000000004088e8 in tcp_connect (tcp=tcp@entry=0x7ffff7fbb3a8,
    hostname=hostname@entry=0x7ffff7fb7b3c "dumps.wikimedia.org", port=port@entry=443,
    secure=secure@entry=1, local_if=0x60e088 "",
    message=message@entry=0x7ffff7fba780 "Connection gone.\n",
    io_timeout=io_timeout@entry=120) at tcp.c:86
#6  0x0000000000407718 in http_connect (conn=conn@entry=0x7ffff7fb9780, proto=3,
    proxy=proxy@entry=0x0, host=host@entry=0x7ffff7fb7b3c "dumps.wikimedia.org",
    port=443, user=user@entry=0x7ffff7fb873c "", pass=pass@entry=0x7ffff7fb8b3c "",
    io_timeout=120) at http.c:119
#7  0x0000000000406248 in conn_init (conn=conn@entry=0x7ffff7fb7b28) at conn.c:233
#8  0x000000000040649b in conn_setup (conn=conn@entry=0x7ffff7fb7b28) at conn.c:250
#9  0x000000000040483b in setup_thread (c=0x7ffff7fb7b28) at axel.c:777
#10 0x00007ffff756fdc5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff729e76d in clone () from /lib64/libc.so.6
```

**Comment by ordex** [comment] 2018-01-01 14:00
just to be sure, are you running master or 2.16.1 ?

**Comment by maplewizard** [comment] 2018-01-01 14:02
I tested both and they both failed. This log is from 2.16.1.

**Comment by jotline** [comment] 2018-10-26 07:05
It seems a bug for 2.16.1, when  I  am running in version 2.10, then everything works fine.

**Comment by ismaell** [comment] 2019-05-14 21:09
This should have been fixed in some of the recent changes to the conn/http code.

**Closed by ismaell** 2019-05-14 21:09 UTC
