### ISSUE TITLE
2.17.3 produces some warning when building

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#219] opened 2019-06-11 18:02 UTC
Hi folks!

When building Axel 2.17.3 on Debian Sid, I can see:

```
Making all in src
make[3]: Entering directory '/PKGS/axel2/axel/src'
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o axel.o axel.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o conf.o conf.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o conn.o conn.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o ftp.o ftp.c
conn.c: In function ‘conn_info’:
conn.c:385:42: warning: ‘%s’ directive writing up to 1023 bytes into a region of size between 1005 and 2040 [-Wformat-overflow=]
     sprintf(conn->http->headers, "%s%s:%i%s",
                                          ^~
conn.c:387:30:
      conn->host, conn->port, s);
                              ~            
In file included from /usr/include/stdio.h:873,
                 from axel.h:52,
                 from conn.c:45:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 9 and 2067 bytes into a destination of size 2048
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o http.o http.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o search.o search.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o ssl.o ssl.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o tcp.o tcp.c
gcc -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall -c -o text.o text.c
text.c: In function ‘main’:
text.c:361:42: warning: ‘.st’ directive output may be truncated writing 3 bytes into a region of size between 1 and 1024 [-Wformat-truncation=]
    snprintf(statefn, sizeof(statefn), "%s.st",
                                          ^~~
In file included from /usr/include/stdio.h:873,
                 from axel.h:52,
                 from text.c:45:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 4 and 1027 bytes into a destination of size 1024
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
text.c:345:40: warning: ‘.st’ directive output may be truncated writing 3 bytes into a region of size between 0 and 1023 [-Wformat-truncation=]
   snprintf(statefn, MAX_STRING - 1, "%s.st", fn);
                                        ^~~
In file included from /usr/include/stdio.h:873,
                 from axel.h:52,
                 from text.c:45:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 4 and 1027 bytes into a destination of size 1023
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc  -g -O2 -fdebug-prefix-map=/PKGS/axel2/axel=. -fstack-protector-strong -Wformat -Werror=format-security -pthread -Wall  -Wl,-z,relro -Wl,-z,now -o axel axel.o conf.o conn.o ftp.o http.o search.o ssl.o tcp.o text.o -lssl -lcrypto -lm 
make[3]: Leaving directory '/PKGS/axel2/axel/src'
```

For a complete log, you can access Debian Buildd System[1] and click over any 'Installed' word.

[1] https://buildd.debian.org/status/package.php?p=axel&suite=experimental

Cheers,

Eriberto

**Comment by ismaell** [comment] 2019-06-11 21:53
I'm working on those and others.

**Comment by ismaell** [comment] 2019-07-07 22:43
Should be fixed in current head (f1a6c1d608ac857d1914d6a4b270b8c3d6a324b4). Needs testing.

**Comment by eribertomota** [comment] 2019-07-08 05:18
Please, see the attached file.

[axel.build.zip](https://github.com/axel-download-accelerator/axel/files/3366762/axel.build.zip)

**Comment by ismaell** [comment] 2019-07-08 08:35
@eribertomota Thanks. For some reason I'm not getting `-Wjump-misses-init` added by the configure script, and it's not part of `-Wall`; is that something buildd is adding?

**Comment by eribertomota** [comment] 2019-07-08 15:50
I got it in a fresh jail Sid but you can use cowbuilder.

1. Unzip attached file.
2. Install and prepare cowbuilder for Sid:

```
# apt-get install cowbuilder
# cowbuilder create
```

3. Build the package using cowbuilder:

`# cowbuilder build axel_2.17.3+git20190705.f1a6c1d-1.dsc`

Thanks

[axel-debpkg.zip](https://github.com/axel-download-accelerator/axel/files/3369161/axel-debpkg.zip)

**Comment by ismaell** [comment] 2019-07-09 09:50
I've fixed more of them yesterday night. Let's see if that's enough.

**Comment by eribertomota** [comment] 2019-07-09 18:13
Worked fine, thanks!

However, autotools says:

configure.ac:120: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:120: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:120: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

I think maybe you can update it.

**Comment by ismaell** [comment] 2019-07-10 11:05
> Worked fine, thanks!
> 
> However, autotools says:
> 
> configure.ac:120: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
> configure.ac:120: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
> configure.ac:120: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
> 
> I think maybe you can update it.

The warning is old; it's caused by `AM_GNU_GETTEXT_VERSION([0.18])`.

**Comment by ismaell** [comment] 2019-07-10 11:11
I'll just go ahead and change the required gettext version (for an older one to avoid breaking anything).

**Closed by ismaell** 2019-07-10 11:11 UTC
Labels: build warnings

**Comment by eribertomota** [comment] 2019-07-11 01:33
Em qua, 10 de jul de 2019 às 08:11, Ismael Luceno
<notifications@github.com> escreveu:
>
> I'll just go ahead and change the required gettext version (for an older one to avoid breaking anything).

Thanks!
