### ISSUE TITLE
Axel fails to download with option --quite 

### ISSUE THREAD

**Issue by S-Aarab** [axel-download-accelerator/axel#134] opened 2017-10-21 08:52 UTC
Axel fails to download files if you used with one of:
-  '--quiet' option.
- 'verbose = 0' in config file.
- 'verbose = -1' in config file.

```
$ axel --version

Axel version 2.15 (Linux)

Copyright 2001-2007 Wilmer van der Gaast,
          2007-2009 Giridhar Appaji Nag,
          2008-2010 Philipp Hagemeister,
          2015-2017 Joao Eriberto Mota Filho,
          2016-2017 Stephen Thirlwall,
          2017      Ismael Luceno,
          2017      Antonio Quartulli,
                    and others.
Please, see the CREDITS file.
```
```
$ axel --quiet 'http://ipv4.download.thinkbroadband.com/5MB.zip'
$ du 5MB.zip 
0       5MB.zip
```
```
$ echo "verbose = 0" > ~/.axelrc
$ axel 'http://ipv4.download.thinkbroadband.com/5MB.zip'
Initializing download: http://ipv4.download.thinkbroadband.com/5MB.zip


Downloaded 0 byte in 0 seconds. (0.00 KB/s)
```
```
$ echo "verbose = -1" > ~/.axelrc
$ axel 'http://ipv4.download.thinkbroadband.com/5MB.zip'
Initializing download: http://ipv4.download.thinkbroadband.com/5MB.zip


Downloaded 0 byte in 0 seconds. (0.00 KB/s)
```
```
$ rm ~/.axelrc
$ axel 'http://ipv4.download.thinkbroadband.com/5MB.zip'
Initializing download: http://ipv4.download.thinkbroadband.com/5MB.zip
File size: 5242880 bytes
Opening output file 5MB.zip
Starting download
.
.
.
Downloaded 5.0 Megabyte in 12 seconds. (395.17 KB/s)
$ du 5MB.zip 
5120    5MB.zip
```

**Comment by ismaell** [comment] 2017-10-21 08:54
Duplicate of #133

**Closed** 2017-10-21 08:54 UTC
