### ISSUE TITLE
binary file lead to "tar: Skipping to next header"

### ISSUE THREAD

**Issue by phoemc** [axel-download-accelerator/axel#361] opened 2021-10-18 17:18 UTC
- I used axel to download hdF5 (binary) file, but failed to decompress .tar.gz file.Every time you apply pressure, you will encounter the problem of `tar: Skipping to next header`.
- The file I downloaded was a huge one, 200 gigabytes in size; It contains numerous HDF5 files.For details, please refer to the [Megadepth](https://www.cs.cornell.edu/projects/megadepth/).`Strangely enough, it always breaks at about 150 gigabytes` .
So I came up with a way that is to use aria2 to relay axel download, and can achieve all the data download down. But the first problem remains unsolved.
```
axel https://www.cs.cornell.edu/projects/megadepth/dataset/Megadepth_v1/MegaDepth_v1.tar.gz
```
The above command line will probably download 150 to 180 gigabytes of data, followed by aria2：
```
aria2 -c https://www.cs.cornell.edu/projects/megadepth/dataset/Megadepth_v1/MegaDepth_v1.tar.gz
```
After the above two processes, the data is all down, but there will be problems when decompressing.
```
tar -xzvf MegaDepth_v1.tar.gz
```
reporting an error：`tar: Skipping to next header`
How to solve this problem.

**Comment by ismaell** [comment] 2021-10-18 22:15
I would need to know how the download operation fails with axel, and if possible, the state (`.st`) file.

**Comment by ismaell** [comment] 2022-11-07 19:12
Closing due to lack of information to reproduce the issue.

**Closed by ismaell** 2022-11-07 19:12 UTC
Labels: invalid
