### ISSUE TITLE
HTTP CONNECT Proxying method lacks authentication headers

### ISSUE THREAD

**Issue by tkasarla** [axel-download-accelerator/axel#216] opened 2019-05-30 11:43 UTC
My proxy requires authentication. I have added the proxy in the format 'http://username:password@proxy-address:port/'. However, I get a HTTP/1.1 407 Proxy Authentication Required error.

Same download works through wget, so I am sure it's not the proxy server issue.

How do I fix this?

**Comment by ismaell** [comment] 2019-05-30 12:58
That code path has not been exercised much; if you can, please implement test cases.

**Comment by ismaell** [comment] 2019-05-30 13:01
The code that executes the authentication is under `http.c` in the `http_get` function.

**Comment by ismaell** [comment] 2019-05-30 13:09
Run wget and axel in debugging mode and compare the headers sent to the proxy and server respectively.

A quick look at the source tells me nobody ever tried HTTPS/FTP over an HTTP proxy, so it's probably not building the header at all.

It does the trick for an HTTP over HTTP proxy session because there is no encapsulation, it reuses the GET method, so it works a little bit differently.

**Comment by shankar** [comment] 2019-09-19 23:38
@tkasarla `407 Proxy Authentication Required` status response is triggered cuz axel is not able to provide the right credentials to the proxy server. looks like the **`base64`** encoder is buggy. 
I tested HTTP authentication with axel and it sent the wrong credentials

#### Reproducing the bug:
URL: `https://username:password@httpbin.org/basic-auth/username/password`
_Browser request authorization header_: 
`Authorization:  Basic dXNlcm5hbWU6cGFzc3dvcmQ=`
_Axel request authorization header:_
`Authorization: Basic dXNlcm5hbWU6`

The same code provides credentials for `Proxy-Authorization` header.
This is probably the code that is buggy:
https://github.com/axel-download-accelerator/axel/blob/c5c83e6ad8132cb99d62e8978b1ab60c75f72668/src/http.c#L67-L95

@ismaell is this right ? may i work on this bug ?

**Comment by ismaell** [comment] 2019-09-20 12:49
@shankar go ahead. From what you mention, it seems `http_auth_token` is getting `pass==NULL`, that's the problem, the base64 encoding looks fine.

**Comment by shankar** [comment] 2019-09-23 11:10
@ismaell i checked and looks like the while loop in `http_auth_token` is prematurely ending. I have fixed it. Pls comment on my pull request.

**Comment by ismaell** [comment] 2019-09-23 11:59
@shankar please note that the flaw you fixed isn't enough to make proxy auth work on all cases, it'll need some more effort.

**Comment by shankar** [comment] 2019-09-23 13:45
@ismaell i have tested the code against credentials of various lengths and it worked in all the cases. I checked with curl and wget projects and none of those seem to have comprehensive unit tests. Please let me know if u find a case where it fails because for now i don't know how to proceed.

**Comment by ismaell** [comment] 2019-09-23 14:21
@shankar please see around lines 180-200 in `http.c`. It adds the proxy auth on the HTTP stream, but that wouldn't work for HTTPS.

**Comment by shankar** [comment] 2019-09-23 17:20
@ismaell now i understand. For now this code should work fine. The proxy will receive the `Proxy-Authorization` and fetch the HTTPS destinations just like GET request to HTTP sites.

Later when we implement CONNECT method this would be a problem since this method is not idempotent.

Later while implementing CONNECT method to tunnel through proxy care should be taken to provide `Proxy-Authorization` header to proxy only and destination bound headers should be provided when the tunnel is secured.

This should be the case or i am unable to understand you.

**Comment by ismaell** [comment] 2019-09-23 20:46
@shankar Correct.

I will close this one and add another issue for the HTTPS proxying and add a note there.

**Closed by ismaell** 2019-09-23 20:46 UTC
Labels: bug, help wanted
